# Generated by Django 3.0.4 on 2020-03-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.TextField(default='name', verbose_name='Имя пользователя'),
        ),
    ]
