# Generated by Django 3.0.4 on 2020-03-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0003_auto_20200321_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
